import React from "react";
import { Ionicons } from "@expo/vector-icons";

const ICON_MAP = {
  coffee: "cafe",
  home: "home",
  menu: "menu",
  back: "arrow-back",
  forward: "arrow-forward",
  bell: "notifications",
  "bell-outline": "notifications-outline",
  search: "search",
  cart: "cart",
  person: "person",
  people: "people",
  settings: "settings",
  lock: "lock-closed",
  eye: "eye",
  "eye-off": "eye-off",
  check: "checkmark",
  "check-circle": "checkmark-circle",
  warning: "warning",
  alert: "alert-circle",
  clipboard: "clipboard",
  list: "list",
  flame: "flame",
  cube: "cube",
  receipt: "receipt",
  card: "card",
  cash: "cash",
  phone: "phone-portrait",
  calendar: "calendar",
  time: "time",
  location: "location",
  camera: "camera",
  cloud: "cloud",
  wifi: "wifi",
  info: "information-circle",
  refresh: "refresh",
  swap: "swap-horizontal",
  add: "add",
  close: "close",
  edit: "create",
  trash: "trash",
  flash: "flash",
  "volume-high": "volume-high",
  key: "key",
  "log-out": "log-out",
  "bar-chart": "bar-chart",
  happy: "happy",
  restaurant: "restaurant",
  star: "star",
  ellipsis: "ellipsis-horizontal",
  chevron: "chevron-forward",
};

export default function Icon({ name, size = 20, color = "#2D1E16", style }) {
  const ionName = ICON_MAP[name] || name;
  return <Ionicons name={ionName} size={size} color={color} style={style} />;
}
